<?xml version="1.0"?>
<package format="3">
  <name>datalogger</name>
  <version>0.0.1</version>
  <description>Basic ROS 2 package for logging and testing a simple C++ node.</description>
  <maintainer email="rosdev@example.com">rosdev</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

